# Generated by Django 6.0.6 on 2026-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_category_prompt_comment_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="avatars/default.png", upload_to="avatars/"
            ),
        ),
    ]
