# Generated by Django 6.0.6 on 2026-07-05 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
