# Generated by Django 6.0.6 on 2026-07-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0004_alter_rate_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="prompt",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.RemoveConstraint(
            model_name="rate",
            name="unique_rate",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Rate",
        ),
    ]
