# Generated by Django 6.0.6 on 2026-07-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0005_remove_comment_prompt_remove_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
